apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}  # ClusterIP or NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.nginx.name }}
  {{- if and (eq .Values.service.type "NodePort") .Values.service.externalPolicyLocal }}
  externalTrafficPolicy: Local
  {{- end }}
