{{/*
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: dcorch-bin
data:
  dcorch-api.sh: |
{{ tuple "bin/_dcorch-api.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  dcorch-engine-worker.sh: |
{{ tuple "bin/_dcorch-engine-worker.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  dcorch-engine.sh: |
{{ tuple "bin/_dcorch-engine.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  dcorch-identity-api-proxy.sh: |
{{ tuple "bin/_dcorch-identity-api-proxy.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  dcorch-sysinv-api-proxy.sh: |
{{ tuple "bin/_dcorch-sysinv-api-proxy.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  dcorch-patch-api-proxy.sh: |
{{ tuple "bin/_dcorch-patch-api-proxy.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  dcorch-usm-api-proxy.sh: |
{{ tuple "bin/_dcorch-usm-api-proxy.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  db-init.py: |
{{- include "helm-toolkit.scripts.db_init" . | indent 4 }}
  db-sync.sh: |
{{ tuple "bin/_db-sync.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  db-drop.sh: |
{{ tuple "bin/_db-drop.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  db-drop.py: |
{{- include "helm-toolkit.scripts.db_drop" . | indent 4 }}
  ks-service.sh: |
{{- include "helm-toolkit.scripts.keystone_service" . | indent 4 }}
  ks-endpoints.sh: |
{{- include "helm-toolkit.scripts.keystone_endpoints" . | indent 4 }}
  ks-user.sh: |
{{- include "helm-toolkit.scripts.keystone_user" . | indent 4 }}
