{{/*
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- define "dcOrchApiLivenessProbeTemplate" }}
tcpSocket:
  port: {{ tuple "dcorch" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
{{- end }}

{{- if .Values.manifests.deployment_api }}
{{- $envAll := . }}

{{- $mounts_dcorch_api := .Values.pod.mounts.api.dcorch }}
{{- $mounts_dcorch_api_init := .Values.pod.mounts.api.init_container }}

{{- $serviceAccountName := "dcorch" }}
{{ tuple $envAll "api" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcorch-api
  labels:
{{ tuple $envAll "dcorch" "api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  {{- if not .Values.pod.autoscaling.enabled }}
  replicas: {{ .Values.pod.replicas.api }}
  {{- end }}
  selector:
    matchLabels:
{{ tuple $envAll "dcorch" "api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | indent 2 }}
  template:
    metadata:
      {{- with .Values.pod.annotations.api }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
{{ tuple $envAll "dcorch" "api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      initContainers:
{{ tuple $envAll "api" $mounts_dcorch_api_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: dcorch
{{ tuple $envAll $envAll.Values.pod.resources.api | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          env:
          - name: SSL_CERT_FILE
            value: /etc/ssl/certs/ca-certificates.crt
          envFrom:
            - secretRef:
                name: dcorch-keystone-admin
          volumeMounts:
            - name: dcorch-bin
              mountPath: /tmp/dcorch-api.sh
              subPath: dcorch-api.sh
              readOnly: true
            - name: dcorch-etc
              mountPath: /etc/dcorch/dcorch.conf
              subPath: dcorch.conf
              readOnly: true
            - name: dcorch-etc
              mountPath: /etc/dcorch/logging.conf
              subPath: logging.conf
              readOnly: true
            - name: dc-vault-dir
              mountPath: {{ .Values.conf.dcorch.vault.base_path }}
            - name: dc-backup-dir
              mountPath: {{ .Values.conf.dcorch.backup.base_path }}
{{- if .Values.secrets.caCertSecret }}
            - name: ca-certs
              mountPath: /etc/pki/ca-trust/source/anchors/dcorch-local-ca.crt
              subPath: ca.crt
              readOnly: true
{{- end }}
{{ if $mounts_dcorch_api.volumeMounts }}{{ toYaml $mounts_dcorch_api.volumeMounts | indent 12 }}{{ end }}
{{- dict "enabled" .Values.manifests.certificates "name" .Values.secrets.tls.dcorch.api.public | include "helm-toolkit.snippets.tls_volume_mount" | indent 12 }}
{{ dict "envAll" . "component" "api" "container" "default" "type" "liveness" "probeTemplate" (include "dcOrchApiLivenessProbeTemplate" . | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
          command:
            - /tmp/dcorch-api.sh
          image: "{{ .Values.images.tags.dcorch }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ tuple "dcorch" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
              protocol: TCP
{{ tuple $envAll "dcorch" | include "helm-toolkit.snippets.kubernetes_image_pull_secrets" | indent 6 }}
      nodeSelector:
        {{ .Values.labels.dcorch.node_selector_key }}: {{ .Values.labels.dcorch.node_selector_value }}
{{ if $envAll.Values.pod.tolerations.dcorch.enabled }}
{{ tuple $envAll "dcorch" | include "helm-toolkit.snippets.kubernetes_tolerations" | indent 6 }}
{{ end }}
      affinity:
        {{ tuple $envAll "dcorch" "api" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      volumes:
        - name: dcorch-etc
          secret:
            secretName: dcorch-etc
            defaultMode: 0644
        - name: dcorch-bin
          configMap:
            name: dcorch-bin
            defaultMode: 0755
{{- if .Values.secrets.caCertSecret }}
        - name: ca-certs
          secret:
            secretName: {{ .Values.secrets.caCertSecret }}
            defaultMode: 0644
{{- end }}
        {{- if and .Values.volume.vault.enabled  .Values.manifests.pvc_vault }}
        - name: dc-vault-dir
          persistentVolumeClaim:
            claimName: dc-vault-pvc
        {{- else }}
        - name: dc-vault-dir
          hostPath:
            path: {{ .Values.conf.dcorch.vault.base_path }}
            type: DirectoryOrCreate
        {{- end }}
        {{- if and .Values.volume.backup.enabled  .Values.manifests.pvc_backup }}
        - name: dc-backup-dir
          persistentVolumeClaim:
            claimName: dc-backup-pvc
        {{- else }}
        - name: dc-backup-dir
          hostPath:
            path: {{ .Values.conf.dcorch.backup.base_path }}
            type: DirectoryOrCreate
        {{- end }}
{{ if $mounts_dcorch_api.volumes }}{{ toYaml $mounts_dcorch_api.volumes | indent 8 }}{{ end }}
{{- dict "enabled" .Values.manifests.certificates "name" .Values.secrets.tls.dcorch.api.public | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{- end }}
