{{/*
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if empty .Values.conf.dcorch.database.connection -}}
{{- $connection := tuple "oslo_db" "internal" "dcorch" "postgresql" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup" -}}
{{- $_ := set .Values.conf.dcorch.database "connection" $connection -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.DEFAULT.sql_connection -}}
{{- $_ := tuple "oslo_db" "internal" "dcorch" "postgresql" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup"| set .Values.conf.dcorch.DEFAULT "sql_connection" -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.keystone_authtoken.auth_uri -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.dcorch.keystone_authtoken "auth_uri" -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.keystone_authtoken.auth_url -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.dcorch.keystone_authtoken "auth_url" -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.keystone_authtoken.region_name -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "region_name" .Values.endpoints.identity.auth.dcorch.region_name -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.keystone_authtoken.project_name -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "project_name" .Values.endpoints.identity.auth.dcorch.project_name -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.keystone_authtoken.project_domain_name -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "project_domain_name" .Values.endpoints.identity.auth.dcorch.project_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.keystone_authtoken.user_domain_name -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "user_domain_name" .Values.endpoints.identity.auth.dcorch.user_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.keystone_authtoken.username -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "username" .Values.endpoints.identity.auth.dcorch.username -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.keystone_authtoken.password -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "password" .Values.endpoints.identity.auth.dcorch.password -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.keystone_authtoken.interface -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "interface" (default "internal" .Values.endpoints.identity.auth.dcorch.interface) -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.endpoint_cache.auth_uri -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.dcorch.keystone_authtoken "auth_uri" -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.endpoint_cache.region_name -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "region_name" .Values.endpoints.identity.auth.dcorch.region_name -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.endpoint_cache.project_name -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "project_name" .Values.endpoints.identity.auth.dcorch.project_name -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.endpoint_cache.project_domain_name -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "project_domain_name" .Values.endpoints.identity.auth.dcorch.project_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.endpoint_cache.user_domain_name -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "user_domain_name" .Values.endpoints.identity.auth.dcorch.user_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.endpoint_cache.username -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "username" .Values.endpoints.identity.auth.dcorch.username -}}
{{- end -}}
{{- if empty .Values.conf.dcorch.endpoint_cache.password -}}
{{- $_ := set .Values.conf.dcorch.keystone_authtoken "password" .Values.endpoints.identity.auth.dcorch.password -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: dcorch-etc
type: Opaque
data:
  dcorch.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.dcorch | b64enc }}
  logging.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.logging | b64enc }}
  api-paste.ini: {{ .Values.conf.api_paste.content | b64enc }}
