{{- $envAll := . }}

{{- if .Values.manifests.service_keystone_api }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tuple "keystone-api-proxy" "internal" $envAll | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
  ports:
  - name: ks-api-proxy
    port: {{ .Values.network.keystone_api_proxy.port }}
    {{ if .Values.network.keystone_api_proxy.node_port.enabled }}
    nodePort: {{ .Values.network.keystone_api_proxy.node_port.port }}
    {{ end }}
  selector:
{{ tuple $envAll "dcorch" "keystone-api-proxy" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{ if .Values.network.keystone_api_proxy.external_policy_local }}
  externalTrafficPolicy: Local
  {{ end }}
{{- end }}
