#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: dc-vault-nginx
  labels:
    chart_group: dc-vault-nginx
spec:
  releaseName: dc-vault-nginx
  chart:
    spec:
      chart: dc-vault-nginx
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: dc-vault-nginx-static-overrides
      valuesKey: dc-vault-nginx-static-overrides.yaml
    - kind: Secret
      name: dc-vault-nginx-system-overrides
      valuesKey: dc-vault-nginx-system-overrides.yaml
